export const lettersData = {
  vowels: [
    { character: 'अ', pronunciation: 'ah' },
    { character: 'आ', pronunciation: 'aah' },
    { character: 'इ', pronunciation: 'e' },
    { character: 'ई', pronunciation: 'ee' },
    { character: 'उ', pronunciation: 'ou' },
    { character: 'ऊ', pronunciation: 'oo' },
    { character: 'ए', pronunciation: 'ae' },
    { character: 'ऐ', pronunciation: 'ai' },
    { character: 'ओ', pronunciation: 'o' },
    { character: 'औ', pronunciation: 'au' },
    { character: 'अं', pronunciation: 'am' },
    { character: 'अः', pronunciation: 'ah' },
    { character: 'ऋ', pronunciation: 'ṛi' },
    { character: 'ॠ', pronunciation: 'ṝi' },
    { character: 'ऌ', pronunciation: 'ḷi' },
    { character: 'ॡ', pronunciation: 'ḹi' },
    { character: 'ऑ', pronunciation: 'aw' },
  ].filter(item => item.character),
  consonants: [
    { character: 'क', pronunciation: 'ka' },
    { character: 'ख', pronunciation: 'kha' },
    { character: 'ग', pronunciation: 'ga' },
    { character: 'घ', pronunciation: 'gha' },
    { character: 'ङ', pronunciation: 'anga' },
    { character: 'च', pronunciation: 'cha' },
    { character: 'छ', pronunciation: 'chha' },
    { character: 'ज', pronunciation: 'ja' },
    { character: 'झ', pronunciation: 'jha' },
    { character: 'ञ', pronunciation: 'nya' },
    { character: 'ट', pronunciation: 'ṭa' },
    { character: 'ठ', pronunciation: 'ṭha' },
    { character: 'ड', pronunciation: 'ḍa' },
    { character: 'ढ', pronunciation: 'ḍha' },
    { character: 'ण', pronunciation: 'ṇuh' },
    { character: 'त', pronunciation: 'ta' },
    { character: 'थ', pronunciation: 'tha' },
    { character: 'द', pronunciation: 'the' },
    { character: 'ध', pronunciation: 'dha' },
    { character: 'न', pronunciation: 'na' },
    { character: 'प', pronunciation: 'pa' },
    { character: 'फ', pronunciation: 'pha' },
    { character: 'ब', pronunciation: 'ba' },
    { character: 'भ', pronunciation: 'bha' },
    { character: 'म', pronunciation: 'ma' },
    { character: 'य', pronunciation: 'ya' },
    { character: 'र', pronunciation: 'ra' },
    { character: 'ल', pronunciation: 'la' },
    { character: 'व', pronunciation: 'va' },
    { character: 'श', pronunciation: 'sha' },
    { character: 'ष', pronunciation: 'ṣa' },
    { character: 'स', pronunciation: 'sa' },
    { character: 'ह', pronunciation: 'ha' },
    { character: 'ळ', pronunciation: 'ada' },
    { character: 'क्ष', pronunciation: 'kṣa' },
    { character: 'ज्ञ', pronunciation: 'dnya' },
  ].filter(item => item.character),
  dependingVowels: [
    { character: 'ा', pronunciation: 'ah' },
    { character: 'ि', pronunciation: 'eh' },
    { character: 'ु', pronunciation: 'oh' },
    { character: 'े', pronunciation: 'ae' },
    { character: 'ो', pronunciation: 'o' },
    { character: 'ै', pronunciation: 'ai' },
    { character: 'ौ', pronunciation: 'au' },
  ].filter(item => item.character),
};

export const wordsData = {
  common: [
    { word: 'है', pronunciation: 'hai' },
    { word: 'में', pronunciation: 'mein' },
    { word: 'से', pronunciation: 'se' },
    { word: 'हैं', pronunciation: 'hain' },
    { word: 'का', pronunciation: 'ka' },
    { word: 'एक', pronunciation: 'ek' },
    { word: 'पर', pronunciation: 'par' },
    { word: 'इस', pronunciation: 'is' },
    { word: 'के', pronunciation: 'ke' },
    { word: 'साथ', pronunciation: 'saath' },
    { word: 'उस', pronunciation: 'us' },
    { word: 'की', pronunciation: 'ki' },
    { word: 'किया', pronunciation: 'kiya' },
    { word: 'जा', pronunciation: 'ja' },
    { word: 'दिन', pronunciation: 'din' },
    { word: 'कहा', pronunciation: 'kaha' },
    { word: 'रहा', pronunciation: 'raha' },
    { word: 'कुछ', pronunciation: 'kuch' },
    { word: 'करना', pronunciation: 'karna' },
    { word: 'बहुत', pronunciation: 'bahut' },
    { word: 'होता', pronunciation: 'hota' },
    { word: 'भी', pronunciation: 'bhi' },
    { word: 'कभी', pronunciation: 'kabhi' },
    { word: 'कोई', pronunciation: 'koi' },
    { word: 'जैसा', pronunciation: 'jaisa' },
    { word: 'उनका', pronunciation: 'unka' },
    { word: 'यह', pronunciation: 'yah' },
    { word: 'आप', pronunciation: 'aap' },
    { word: 'कहानी', pronunciation: 'kahani' },
    { word: 'हम', pronunciation: 'ham' },
    { word: 'वह', pronunciation: 'vah' },
    { word: 'फिर', pronunciation: 'phir' },
    { word: 'आज', pronunciation: 'aaj' },
    { word: 'यहाँ', pronunciation: 'yahan' },
    { word: 'अब', pronunciation: 'ab' },
    { word: 'क्या', pronunciation: 'kya' },
    { word: 'कर', pronunciation: 'kar' },
    { word: 'रहे', pronunciation: 'rahe' },
    { word: 'आपका', pronunciation: 'aapka' },
    { word: 'को', pronunciation: 'ko' },
    { word: 'हो', pronunciation: 'ho' },
    { word: 'जिंदगी', pronunciation: 'zindagi' },
    { word: 'मुझे', pronunciation: 'mujhe' },
    { word: 'सकता', pronunciation: 'sakta' },
    { word: 'बना', pronunciation: 'bana' },
    { word: 'जो', pronunciation: 'jo' },
    { word: 'करता', pronunciation: 'karta' },
    { word: 'जैसे', pronunciation: 'jaise' },
    { word: 'हुआ', pronunciation: 'hua' },
    { word: 'दूसरे', pronunciation: 'dusre' },
    { word: 'सब', pronunciation: 'sab' },
    { word: 'उसे', pronunciation: 'use' },
    { word: 'दो', pronunciation: 'do' },
    { word: 'बार', pronunciation: 'baar' },
    { word: 'लिए', pronunciation: 'liye' },
    { word: 'हुए', pronunciation: 'hue' },
    { word: 'अपने', pronunciation: 'apne' },
    { word: 'पास', pronunciation: 'paas' },
    { word: 'होते', pronunciation: 'hote' },
    { word: 'वे', pronunciation: 've' },
    { word: 'दिल', pronunciation: 'dil' },
    { word: 'बात', pronunciation: 'baat' },
    { word: 'था', pronunciation: 'tha' },
    { word: 'वही', pronunciation: 'vahi' },
    { word: 'तक', pronunciation: 'tak' },
    { word: 'समय', pronunciation: 'samay' },
    { word: 'अपनी', pronunciation: 'apni' },
    { word: 'जब', pronunciation: 'jab' },
    { word: 'तुम', pronunciation: 'tum' },
    { word: 'आदि', pronunciation: 'aadi' },
    { word: 'यही', pronunciation: 'yahi' },
    { word: 'रूप', pronunciation: 'roop' },
    { word: 'समझा', pronunciation: 'samjha' },
    { word: 'बारे', pronunciation: 'baare' },
  ].filter(item => item.word),
};

export const sentencesData = [
  {
    lessonNumber: 1,
    url: 'lesson-1',
    title: 'कैफ़े में ऑर्डर करना',
    titleEn: 'Ordering in a Cafe',
    emoji: '☕',
    color: 'from-blue-500 to-blue-600',
    sentences: [
      { sentence: 'कृपया मुझे एक कॉफ़ी दीजिए।', pronunciation: 'Krupaya mujhe ek coffee dijiye.' },
      { sentence: 'आपका आर्डर क्या है?', pronunciation: 'Aapka order kya hai?' },
      { sentence: 'मुझे एक चाय मिल सकती है?', pronunciation: 'Mujhe ek chai mil sakti hai?' },
      { sentence: 'ठंडी द्रिंक कहाँ है?', pronunciation: 'Thandi drink kahan hai?' },
      { sentence: 'सैंडविच और बर्गर लाइए।', pronunciation: 'Sandwich aur burger laiye.' },
      { sentence: 'पानी मिलेगा?', pronunciation: 'Paani milega?' },
      { sentence: 'बिल कहाँ चुकाऊं?', pronunciation: 'Bill kahan chukaoon?' },
      { sentence: 'बहुत स्वादिष्ट था।', pronunciation: 'Bahut swadisht tha.' },
      { sentence: 'कितना हुआ?', pronunciation: 'Kitna hua?' },
      { sentence: 'धन्यवाद।', pronunciation: 'Dhanyavad.' },
    ],
  },
  {
    lessonNumber: 2,
    url: 'lesson-2',
    title: 'लोगों का अभिवादन',
    titleEn: 'Greeting People',
    emoji: '🙏',
    color: 'from-orange-500 to-orange-600',
    sentences: [
      { sentence: 'नमस्कार।', pronunciation: 'Namaskar.' },
      { sentence: 'प्रणाम।', pronunciation: 'Pranam.' },
      { sentence: 'आप कैसे हैं?', pronunciation: 'Aap kaise hain?' },
      { sentence: 'मैं ठीक हूँ, धन्यवाद।', pronunciation: 'Main theek hoon, dhanyavad.' },
      { sentence: 'शुभ प्रभात।', pronunciation: 'Shubh Prabhat.' },
      { sentence: 'शुभ संध्या।', pronunciation: 'Shubh Sandhya.' },
      { sentence: 'शुभ रात्रि।', pronunciation: 'Shubh Ratri.' },
      { sentence: 'आपका स्वागत है।', pronunciation: 'Aapka swagat hai.' },
      { sentence: 'आपको मिलकर खुशी हुई।', pronunciation: 'Aapko milkar khushi hui.' },
      { sentence: 'नमस्ते।', pronunciation: 'Namaste.' },
    ],
  },
  {
    lessonNumber: 3,
    url: 'lesson-3',
    title: 'अपना परिचय दें',
    titleEn: 'Describe Yourself',
    emoji: '👤',
    color: 'from-green-500 to-green-600',
    sentences: [
      { sentence: 'मैं दिल्ली से हूँ।', pronunciation: 'Main Delhi se hoon.' },
      { sentence: 'मेरी उम्र पच्चीस साल है।', pronunciation: 'Meri umr pachchis saal hai.' },
      { sentence: 'मैं भारत से हूँ।', pronunciation: 'Main Bharat se hoon.' },
      { sentence: 'मैं अपने परिवार के साथ रहता हूँ।', pronunciation: 'Main apne parivaar ke saath rahta hoon.' },
      { sentence: 'मुझे गाने गाना पसंद है।', pronunciation: 'Mujhe gane gana pasand hai.' },
      { sentence: 'मेरे दो बच्चे हैं।', pronunciation: 'Mere do bachche hain.' },
      { sentence: 'मैं अर्जुन हूँ।', pronunciation: 'Main Arjun hoon.' },
      { sentence: 'मैं हिंदी बोल सकता हूँ।', pronunciation: 'Main Hindi bol sakta hoon.' },
      { sentence: 'मेरा नाम राहुल है।', pronunciation: 'Mera naam Rahul hai.' },
      { sentence: 'मैं विद्यार्थी हूँ।', pronunciation: 'Main vidyarthi hoon.' },
    ],
  },
  {
    lessonNumber: 4,
    url: 'lesson-4',
    title: 'रास्ता पूछना',
    titleEn: 'Asking for Directions',
    emoji: '🗺️',
    color: 'from-red-500 to-red-600',
    sentences: [
      { sentence: 'मुझे यहाँ कैसे पहुँचा जा सकता है?', pronunciation: 'Mujhe yahan kaise pahuncha ja sakta hai?' },
      { sentence: 'यहाँ सबसे नजदीक का बस स्टैंड कहाँ है?', pronunciation: 'Yahan sabse najdeek ka bus stand kahan hai?' },
      { sentence: 'क्या यहाँ कोई मेट्रो स्टेशन है?', pronunciation: 'Kya yahan koi metro station hai?' },
      { sentence: 'कृपया, बाजार का मार्गदर्शन करें।', pronunciation: 'Krupaya, bazaar ka margdarshan karein.' },
      { sentence: 'क्या यहाँ पार्किंग की सुविधा है?', pronunciation: 'Kya yahan parking ki suvidha hai?' },
      { sentence: 'रेलवे स्टेशन कितनी दूर है?', pronunciation: 'Railway station kitni door hai?' },
      { sentence: 'क्या इस इलाके में एक हस्पताल है?', pronunciation: 'Kya is ilake mein ek hospital hai?' },
      { sentence: 'सीधे जाओ।', pronunciation: 'Seedhe jao.' },
      { sentence: 'बाएं मुड़ो।', pronunciation: 'Bayen mudo.' },
      { sentence: 'दाएं मुड़ो।', pronunciation: 'Dayen mudo.' },
    ],
  },
];

export default { lettersData, wordsData, sentencesData };